version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    reviewers:
      - "ksol"
