version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: auto
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: chai
      - dependency-name: eslint
    groups:
      production-minor:
        dependency-type: production
        update-types:
          - minor
        production-patch:
          dependency-type: production
          update-types:
            - patch
        development:
          dependency-type: development
          update-types:
            - minor
            - patch
      linter-packages:
        patterns:
          - "@typescript-eslint/*"
          - "eslint*"
          - "prettier*"
      build-packages:
        patterns:
          - "@babel/*"
          - "@types/*"
          - "core-js"
          - "esbuild"
          - "typescript"
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
