/**
 * @desc
 * Can take the following values:
 * - **pending_dns**: We're waiting for DNS propagation (or the DNS value is not correct)
 * - **new**: The certificate request has been sent to LE
 * - **created**: The certificate has been created and is in use
 * - **dns_required**: (for wildcards only) manual DNS action is required
 * - **error**: There was an error while creating the certificate
 */
export type LetsEncryptStatus =
  | "pending_dns"
  | "new"
  | "created"
  | "dns_required"
  | "error";
export type SslStatus = "pending" | "success" | "error";

export type AcmeDNSError = {
  dns_provider: string;
  variables: string[] | null;
};

/** @see https://developers.scalingo.com/domains */
export interface Domain {
  /** Unique ID of the domain */
  id: string;
  /** Unique ID of the domain's app */
  app_id: string;
  /** Hostname your want to associate with the app */
  name: string;
  /** Creation date of the domain */
  created_at: string;
  /** Subject of the submitted certificate */
  tlscert?: string;
  /** Private key type and length */
  tlskey?: string;
  /** Once a certificate has been submitted, display the validity of it */
  validity?: string;
  /** Wether the domain's certificate is generated by letsencrypt */
  letsencrypt: boolean;
  /** Show the current state of the Let's Encrypt certificate */
  letsencrypt_status: LetsEncryptStatus;
  /** Flag if SSL with a custom certificate is enabled */
  ssl: boolean;
  /** Show the current state of the SSL certificate */
  ssl_status: SslStatus;
  /** The domain is the canonical domain of this application */
  canonical: boolean;
  /** Acme DNS-01 challenge: "name" of the TXT field to set on your domain */
  acme_dns_fqdn: string | null;
  /** Acme DNS-01 challenge: "value" of the TXT field to set on your domain */
  acme_dns_value: string | null;
  /** Acme DNS-01 challenge: wrong configuration (challenge cannot be performed) */
  acme_dns_error: Record<string, never> | AcmeDNSError;
  /** Acme DNS-01 challenge: error(s) during the challenge */
  acme_challenge_error: string | null;
}
