window.esdocSearchIndex = [
  [
    "scalingo/src/collaborators/status.js~accepted",
    "variable/index.html#static-variable-ACCEPTED",
    "<span>ACCEPTED</span> <span class=\"search-result-import-path\">scalingo/src/Collaborators/status.js</span>",
    "variable"
  ],
  [
    "scalingo/src/errors.js~apierror",
    "class/src/errors.js~APIError.html",
    "<span>APIError</span> <span class=\"search-result-import-path\">scalingo/src/errors.js</span>",
    "class"
  ],
  [
    "scalingo/src/addons/index.js~addons",
    "class/src/Addons/index.js~Addons.html",
    "<span>Addons</span> <span class=\"search-result-import-path\">scalingo/src/Addons/index.js</span>",
    "class"
  ],
  [
    "scalingo/src/apps/index.js~apps",
    "class/src/Apps/index.js~Apps.html",
    "<span>Apps</span> <span class=\"search-result-import-path\">scalingo/src/Apps/index.js</span>",
    "class"
  ],
  [
    "scalingo/src/index.js~client",
    "class/src/index.js~Client.html",
    "<span>Client</span> <span class=\"search-result-import-path\">scalingo/src/index.js</span>",
    "class"
  ],
  [
    "scalingo/src/collaborators/index.js~collaborators",
    "class/src/Collaborators/index.js~Collaborators.html",
    "<span>Collaborators</span> <span class=\"search-result-import-path\">scalingo/src/Collaborators/index.js</span>",
    "class"
  ],
  [
    "scalingo/src/containers/index.js~containers",
    "class/src/Containers/index.js~Containers.html",
    "<span>Containers</span> <span class=\"search-result-import-path\">scalingo/src/Containers/index.js</span>",
    "class"
  ],
  [
    "scalingo/src/deployments/index.js~deployments",
    "class/src/Deployments/index.js~Deployments.html",
    "<span>Deployments</span> <span class=\"search-result-import-path\">scalingo/src/Deployments/index.js</span>",
    "class"
  ],
  [
    "scalingo/src/domains/index.js~domains",
    "class/src/Domains/index.js~Domains.html",
    "<span>Domains</span> <span class=\"search-result-import-path\">scalingo/src/Domains/index.js</span>",
    "class"
  ],
  [
    "scalingo/src/notificationplatforms/list.js~email",
    "variable/index.html#static-variable-EMAIL",
    "<span>EMAIL</span> <span class=\"search-result-import-path\">scalingo/src/NotificationPlatforms/list.js</span>",
    "variable"
  ],
  [
    "scalingo/src/environment/index.js~environment",
    "class/src/Environment/index.js~Environment.html",
    "<span>Environment</span> <span class=\"search-result-import-path\">scalingo/src/Environment/index.js</span>",
    "class"
  ],
  [
    "scalingo/src/events/index.js~events",
    "class/src/Events/index.js~Events.html",
    "<span>Events</span> <span class=\"search-result-import-path\">scalingo/src/Events/index.js</span>",
    "class"
  ],
  [
    "scalingo/src/deployments/listener.js~listener",
    "class/src/Deployments/listener.js~Listener.html",
    "<span>Listener</span> <span class=\"search-result-import-path\">scalingo/src/Deployments/listener.js</span>",
    "class"
  ],
  [
    "scalingo/src/logs/index.js~logs",
    "class/src/Logs/index.js~Logs.html",
    "<span>Logs</span> <span class=\"search-result-import-path\">scalingo/src/Logs/index.js</span>",
    "class"
  ],
  [
    "scalingo/src/logs/listener.js~logslistener",
    "class/src/Logs/listener.js~LogsListener.html",
    "<span>LogsListener</span> <span class=\"search-result-import-path\">scalingo/src/Logs/listener.js</span>",
    "class"
  ],
  [
    "scalingo/src/metrics/index.js~metrics",
    "class/src/Metrics/index.js~Metrics.html",
    "<span>Metrics</span> <span class=\"search-result-import-path\">scalingo/src/Metrics/index.js</span>",
    "class"
  ],
  [
    "scalingo/src/notificationplatforms/index.js~notificationplatforms",
    "class/src/NotificationPlatforms/index.js~NotificationPlatforms.html",
    "<span>NotificationPlatforms</span> <span class=\"search-result-import-path\">scalingo/src/NotificationPlatforms/index.js</span>",
    "class"
  ],
  [
    "scalingo/src/notifiers/index.js~notifiers",
    "class/src/Notifiers/index.js~Notifiers.html",
    "<span>Notifiers</span> <span class=\"search-result-import-path\">scalingo/src/Notifiers/index.js</span>",
    "class"
  ],
  [
    "scalingo/src/operations/utils.js~operation",
    "class/src/Operations/utils.js~Operation.html",
    "<span>Operation</span> <span class=\"search-result-import-path\">scalingo/src/Operations/utils.js</span>",
    "class"
  ],
  [
    "scalingo/src/operations/index.js~operations",
    "class/src/Operations/index.js~Operations.html",
    "<span>Operations</span> <span class=\"search-result-import-path\">scalingo/src/Operations/index.js</span>",
    "class"
  ],
  [
    "scalingo/src/collaborators/status.js~pending",
    "variable/index.html#static-variable-PENDING",
    "<span>PENDING</span> <span class=\"search-result-import-path\">scalingo/src/Collaborators/status.js</span>",
    "variable"
  ],
  [
    "scalingo/src/notificationplatforms/list.js~rocket_chat",
    "variable/index.html#static-variable-ROCKET_CHAT",
    "<span>ROCKET_CHAT</span> <span class=\"search-result-import-path\">scalingo/src/NotificationPlatforms/list.js</span>",
    "variable"
  ],
  [
    "scalingo/src/scmintegrations/index.js~scmintegrations",
    "class/src/SCMIntegrations/index.js~SCMIntegrations.html",
    "<span>SCMIntegrations</span> <span class=\"search-result-import-path\">scalingo/src/SCMIntegrations/index.js</span>",
    "class"
  ],
  [
    "scalingo/src/scmrepolinks/index.js~scmrepolinks",
    "class/src/SCMRepoLinks/index.js~SCMRepoLinks.html",
    "<span>SCMRepoLinks</span> <span class=\"search-result-import-path\">scalingo/src/SCMRepoLinks/index.js</span>",
    "class"
  ],
  [
    "scalingo/src/notificationplatforms/list.js~slack",
    "variable/index.html#static-variable-SLACK",
    "<span>SLACK</span> <span class=\"search-result-import-path\">scalingo/src/NotificationPlatforms/list.js</span>",
    "variable"
  ],
  [
    "scalingo/src/tokens/index.js~tokens",
    "class/src/Tokens/index.js~Tokens.html",
    "<span>Tokens</span> <span class=\"search-result-import-path\">scalingo/src/Tokens/index.js</span>",
    "class"
  ],
  [
    "scalingo/src/collaborators/status.js~user_account_deleted",
    "variable/index.html#static-variable-USER_ACCOUNT_DELETED",
    "<span>USER_ACCOUNT_DELETED</span> <span class=\"search-result-import-path\">scalingo/src/Collaborators/status.js</span>",
    "variable"
  ],
  [
    "scalingo/src/users/index.js~users",
    "class/src/Users/index.js~Users.html",
    "<span>Users</span> <span class=\"search-result-import-path\">scalingo/src/Users/index.js</span>",
    "class"
  ],
  [
    "scalingo/src/notificationplatforms/list.js~webhook",
    "variable/index.html#static-variable-WEBHOOK",
    "<span>WEBHOOK</span> <span class=\"search-result-import-path\">scalingo/src/NotificationPlatforms/list.js</span>",
    "variable"
  ],
  [
    "scalingo/src/index.js~clientfromtoken",
    "function/index.html#static-function-clientFromToken",
    "<span>clientFromToken</span> <span class=\"search-result-import-path\">scalingo/src/index.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/addons/index.js",
    "file/src/Addons/index.js.html",
    "src/Addons/index.js",
    "file"
  ],
  [
    "src/addons/index.js~addon",
    "typedef/index.html#static-typedef-Addon",
    "src/Addons/index.js~Addon",
    "typedef"
  ],
  [
    "src/addons/index.js~addonprovider",
    "typedef/index.html#static-typedef-AddonProvider",
    "src/Addons/index.js~AddonProvider",
    "typedef"
  ],
  [
    "src/addons/index.js~addonsso",
    "typedef/index.html#static-typedef-AddonSso",
    "src/Addons/index.js~AddonSso",
    "typedef"
  ],
  [
    "src/addons/index.js~addonupgrade",
    "typedef/index.html#static-typedef-AddonUpgrade",
    "src/Addons/index.js~AddonUpgrade",
    "typedef"
  ],
  [
    "src/addons/index.js~addons#constructor",
    "class/src/Addons/index.js~Addons.html#instance-constructor-constructor",
    "src/Addons/index.js~Addons#constructor",
    "method"
  ],
  [
    "src/addons/index.js~addons#create",
    "class/src/Addons/index.js~Addons.html#instance-method-create",
    "src/Addons/index.js~Addons#create",
    "method"
  ],
  [
    "src/addons/index.js~addons#destroy",
    "class/src/Addons/index.js~Addons.html#instance-method-destroy",
    "src/Addons/index.js~Addons#destroy",
    "method"
  ],
  [
    "src/addons/index.js~addons#for",
    "class/src/Addons/index.js~Addons.html#instance-method-for",
    "src/Addons/index.js~Addons#for",
    "method"
  ],
  [
    "src/addons/index.js~addons#getaddon",
    "class/src/Addons/index.js~Addons.html#instance-method-getAddon",
    "src/Addons/index.js~Addons#getAddon",
    "method"
  ],
  [
    "src/addons/index.js~addons#listcategories",
    "class/src/Addons/index.js~Addons.html#instance-method-listCategories",
    "src/Addons/index.js~Addons#listCategories",
    "method"
  ],
  [
    "src/addons/index.js~addons#listproviders",
    "class/src/Addons/index.js~Addons.html#instance-method-listProviders",
    "src/Addons/index.js~Addons#listProviders",
    "method"
  ],
  [
    "src/addons/index.js~addons#sso",
    "class/src/Addons/index.js~Addons.html#instance-method-sso",
    "src/Addons/index.js~Addons#sso",
    "method"
  ],
  [
    "src/addons/index.js~addons#update",
    "class/src/Addons/index.js~Addons.html#instance-method-update",
    "src/Addons/index.js~Addons#update",
    "method"
  ],
  [
    "src/addons/index.js~category",
    "typedef/index.html#static-typedef-Category",
    "src/Addons/index.js~Category",
    "typedef"
  ],
  [
    "src/addons/index.js~plan",
    "typedef/index.html#static-typedef-Plan",
    "src/Addons/index.js~Plan",
    "typedef"
  ],
  [
    "src/apps/index.js",
    "file/src/Apps/index.js.html",
    "src/Apps/index.js",
    "file"
  ],
  [
    "src/apps/index.js~app",
    "typedef/index.html#static-typedef-App",
    "src/Apps/index.js~App",
    "typedef"
  ],
  [
    "src/apps/index.js~appcreateopts",
    "typedef/index.html#static-typedef-AppCreateOpts",
    "src/Apps/index.js~AppCreateOpts",
    "typedef"
  ],
  [
    "src/apps/index.js~applinks",
    "typedef/index.html#static-typedef-AppLinks",
    "src/Apps/index.js~AppLinks",
    "typedef"
  ],
  [
    "src/apps/index.js~appupdateopts",
    "typedef/index.html#static-typedef-AppUpdateOpts",
    "src/Apps/index.js~AppUpdateOpts",
    "typedef"
  ],
  [
    "src/apps/index.js~apps#all",
    "class/src/Apps/index.js~Apps.html#instance-method-all",
    "src/Apps/index.js~Apps#all",
    "method"
  ],
  [
    "src/apps/index.js~apps#constructor",
    "class/src/Apps/index.js~Apps.html#instance-constructor-constructor",
    "src/Apps/index.js~Apps#constructor",
    "method"
  ],
  [
    "src/apps/index.js~apps#create",
    "class/src/Apps/index.js~Apps.html#instance-method-create",
    "src/Apps/index.js~Apps#create",
    "method"
  ],
  [
    "src/apps/index.js~apps#deploymentlistener",
    "class/src/Apps/index.js~Apps.html#instance-method-deploymentListener",
    "src/Apps/index.js~Apps#deploymentListener",
    "method"
  ],
  [
    "src/apps/index.js~apps#destroy",
    "class/src/Apps/index.js~Apps.html#instance-method-destroy",
    "src/Apps/index.js~Apps#destroy",
    "method"
  ],
  [
    "src/apps/index.js~apps#find",
    "class/src/Apps/index.js~Apps.html#instance-method-find",
    "src/Apps/index.js~Apps#find",
    "method"
  ],
  [
    "src/apps/index.js~apps#logsurl",
    "class/src/Apps/index.js~Apps.html#instance-method-logsURL",
    "src/Apps/index.js~Apps#logsURL",
    "method"
  ],
  [
    "src/apps/index.js~apps#rename",
    "class/src/Apps/index.js~Apps.html#instance-method-rename",
    "src/Apps/index.js~Apps#rename",
    "method"
  ],
  [
    "src/apps/index.js~apps#transfer",
    "class/src/Apps/index.js~Apps.html#instance-method-transfer",
    "src/Apps/index.js~Apps#transfer",
    "method"
  ],
  [
    "src/apps/index.js~apps#update",
    "class/src/Apps/index.js~Apps.html#instance-method-update",
    "src/Apps/index.js~Apps#update",
    "method"
  ],
  [
    "src/collaborators/index.js",
    "file/src/Collaborators/index.js.html",
    "src/Collaborators/index.js",
    "file"
  ],
  [
    "src/collaborators/index.js~collaborator",
    "typedef/index.html#static-typedef-Collaborator",
    "src/Collaborators/index.js~Collaborator",
    "typedef"
  ],
  [
    "src/collaborators/index.js~collaboratorinvitation",
    "typedef/index.html#static-typedef-CollaboratorInvitation",
    "src/Collaborators/index.js~CollaboratorInvitation",
    "typedef"
  ],
  [
    "src/collaborators/index.js~collaborators#constructor",
    "class/src/Collaborators/index.js~Collaborators.html#instance-constructor-constructor",
    "src/Collaborators/index.js~Collaborators#constructor",
    "method"
  ],
  [
    "src/collaborators/index.js~collaborators#destroy",
    "class/src/Collaborators/index.js~Collaborators.html#instance-method-destroy",
    "src/Collaborators/index.js~Collaborators#destroy",
    "method"
  ],
  [
    "src/collaborators/index.js~collaborators#for",
    "class/src/Collaborators/index.js~Collaborators.html#instance-method-for",
    "src/Collaborators/index.js~Collaborators#for",
    "method"
  ],
  [
    "src/collaborators/index.js~collaborators#invite",
    "class/src/Collaborators/index.js~Collaborators.html#instance-method-invite",
    "src/Collaborators/index.js~Collaborators#invite",
    "method"
  ],
  [
    "src/collaborators/index.js~collaborators#inviteaccept",
    "class/src/Collaborators/index.js~Collaborators.html#instance-method-inviteAccept",
    "src/Collaborators/index.js~Collaborators#inviteAccept",
    "method"
  ],
  [
    "src/collaborators/status.js",
    "file/src/Collaborators/status.js.html",
    "src/Collaborators/status.js",
    "file"
  ],
  [
    "src/containers/index.js",
    "file/src/Containers/index.js.html",
    "src/Containers/index.js",
    "file"
  ],
  [
    "src/containers/index.js~container",
    "typedef/index.html#static-typedef-Container",
    "src/Containers/index.js~Container",
    "typedef"
  ],
  [
    "src/containers/index.js~containersize",
    "typedef/index.html#static-typedef-ContainerSize",
    "src/Containers/index.js~ContainerSize",
    "typedef"
  ],
  [
    "src/containers/index.js~containers#availablesizes",
    "class/src/Containers/index.js~Containers.html#instance-method-availableSizes",
    "src/Containers/index.js~Containers#availableSizes",
    "method"
  ],
  [
    "src/containers/index.js~containers#constructor",
    "class/src/Containers/index.js~Containers.html#instance-constructor-constructor",
    "src/Containers/index.js~Containers#constructor",
    "method"
  ],
  [
    "src/containers/index.js~containers#for",
    "class/src/Containers/index.js~Containers.html#instance-method-for",
    "src/Containers/index.js~Containers#for",
    "method"
  ],
  [
    "src/containers/index.js~containers#restart",
    "class/src/Containers/index.js~Containers.html#instance-method-restart",
    "src/Containers/index.js~Containers#restart",
    "method"
  ],
  [
    "src/containers/index.js~containers#scale",
    "class/src/Containers/index.js~Containers.html#instance-method-scale",
    "src/Containers/index.js~Containers#scale",
    "method"
  ],
  [
    "src/containers/index.js~containersoperation",
    "typedef/index.html#static-typedef-ContainersOperation",
    "src/Containers/index.js~ContainersOperation",
    "typedef"
  ],
  [
    "src/deployments/index.js",
    "file/src/Deployments/index.js.html",
    "src/Deployments/index.js",
    "file"
  ],
  [
    "src/deployments/index.js~deployment",
    "typedef/index.html#static-typedef-Deployment",
    "src/Deployments/index.js~Deployment",
    "typedef"
  ],
  [
    "src/deployments/index.js~deploymentlinks",
    "typedef/index.html#static-typedef-DeploymentLinks",
    "src/Deployments/index.js~DeploymentLinks",
    "typedef"
  ],
  [
    "src/deployments/index.js~deploymentpusher",
    "typedef/index.html#static-typedef-DeploymentPusher",
    "src/Deployments/index.js~DeploymentPusher",
    "typedef"
  ],
  [
    "src/deployments/index.js~deploymentstatus",
    "typedef/index.html#static-typedef-DeploymentStatus",
    "src/Deployments/index.js~DeploymentStatus",
    "typedef"
  ],
  [
    "src/deployments/index.js~deployments#constructor",
    "class/src/Deployments/index.js~Deployments.html#instance-constructor-constructor",
    "src/Deployments/index.js~Deployments#constructor",
    "method"
  ],
  [
    "src/deployments/index.js~deployments#find",
    "class/src/Deployments/index.js~Deployments.html#instance-method-find",
    "src/Deployments/index.js~Deployments#find",
    "method"
  ],
  [
    "src/deployments/index.js~deployments#for",
    "class/src/Deployments/index.js~Deployments.html#instance-method-for",
    "src/Deployments/index.js~Deployments#for",
    "method"
  ],
  [
    "src/deployments/index.js~deployments#logs",
    "class/src/Deployments/index.js~Deployments.html#instance-method-logs",
    "src/Deployments/index.js~Deployments#logs",
    "method"
  ],
  [
    "src/deployments/index.js~deploymentsmeta",
    "typedef/index.html#static-typedef-DeploymentsMeta",
    "src/Deployments/index.js~DeploymentsMeta",
    "typedef"
  ],
  [
    "src/deployments/index.js~deploymentsresult",
    "typedef/index.html#static-typedef-DeploymentsResult",
    "src/Deployments/index.js~DeploymentsResult",
    "typedef"
  ],
  [
    "src/deployments/listener.js",
    "file/src/Deployments/listener.js.html",
    "src/Deployments/listener.js",
    "file"
  ],
  [
    "src/deployments/listener.js~eventdeploymentstatusupdated",
    "typedef/index.html#static-typedef-EventDeploymentStatusUpdated",
    "src/Deployments/listener.js~EventDeploymentStatusUpdated",
    "typedef"
  ],
  [
    "src/deployments/listener.js~eventnewdeployment",
    "typedef/index.html#static-typedef-EventNewDeployment",
    "src/Deployments/listener.js~EventNewDeployment",
    "typedef"
  ],
  [
    "src/deployments/listener.js~eventnewdeploymentlog",
    "typedef/index.html#static-typedef-EventNewDeploymentLog",
    "src/Deployments/listener.js~EventNewDeploymentLog",
    "typedef"
  ],
  [
    "src/deployments/listener.js~listener#close",
    "class/src/Deployments/listener.js~Listener.html#instance-method-close",
    "src/Deployments/listener.js~Listener#close",
    "method"
  ],
  [
    "src/deployments/listener.js~listener#constructor",
    "class/src/Deployments/listener.js~Listener.html#instance-constructor-constructor",
    "src/Deployments/listener.js~Listener#constructor",
    "method"
  ],
  [
    "src/deployments/listener.js~listener#onclose",
    "class/src/Deployments/listener.js~Listener.html#instance-method-onClose",
    "src/Deployments/listener.js~Listener#onClose",
    "method"
  ],
  [
    "src/deployments/listener.js~listener#onlog",
    "class/src/Deployments/listener.js~Listener.html#instance-method-onLog",
    "src/Deployments/listener.js~Listener#onLog",
    "method"
  ],
  [
    "src/deployments/listener.js~listener#onnew",
    "class/src/Deployments/listener.js~Listener.html#instance-method-onNew",
    "src/Deployments/listener.js~Listener#onNew",
    "method"
  ],
  [
    "src/deployments/listener.js~listener#onstatus",
    "class/src/Deployments/listener.js~Listener.html#instance-method-onStatus",
    "src/Deployments/listener.js~Listener#onStatus",
    "method"
  ],
  [
    "src/domains/index.js",
    "file/src/Domains/index.js.html",
    "src/Domains/index.js",
    "file"
  ],
  [
    "src/domains/index.js~domain",
    "typedef/index.html#static-typedef-Domain",
    "src/Domains/index.js~Domain",
    "typedef"
  ],
  [
    "src/domains/index.js~domainparams",
    "typedef/index.html#static-typedef-DomainParams",
    "src/Domains/index.js~DomainParams",
    "typedef"
  ],
  [
    "src/domains/index.js~domainupdateparams",
    "typedef/index.html#static-typedef-DomainUpdateParams",
    "src/Domains/index.js~DomainUpdateParams",
    "typedef"
  ],
  [
    "src/domains/index.js~domains#constructor",
    "class/src/Domains/index.js~Domains.html#instance-constructor-constructor",
    "src/Domains/index.js~Domains#constructor",
    "method"
  ],
  [
    "src/domains/index.js~domains#create",
    "class/src/Domains/index.js~Domains.html#instance-method-create",
    "src/Domains/index.js~Domains#create",
    "method"
  ],
  [
    "src/domains/index.js~domains#destroy",
    "class/src/Domains/index.js~Domains.html#instance-method-destroy",
    "src/Domains/index.js~Domains#destroy",
    "method"
  ],
  [
    "src/domains/index.js~domains#for",
    "class/src/Domains/index.js~Domains.html#instance-method-for",
    "src/Domains/index.js~Domains#for",
    "method"
  ],
  [
    "src/domains/index.js~domains#show",
    "class/src/Domains/index.js~Domains.html#instance-method-show",
    "src/Domains/index.js~Domains#show",
    "method"
  ],
  [
    "src/domains/index.js~domains#update",
    "class/src/Domains/index.js~Domains.html#instance-method-update",
    "src/Domains/index.js~Domains#update",
    "method"
  ],
  [
    "src/domains/index.js~letsencryptstatus",
    "typedef/index.html#static-typedef-LetsEncryptStatus",
    "src/Domains/index.js~LetsEncryptStatus",
    "typedef"
  ],
  [
    "src/environment/index.js",
    "file/src/Environment/index.js.html",
    "src/Environment/index.js",
    "file"
  ],
  [
    "src/environment/index.js~environment#bulkdestroy",
    "class/src/Environment/index.js~Environment.html#instance-method-bulkDestroy",
    "src/Environment/index.js~Environment#bulkDestroy",
    "method"
  ],
  [
    "src/environment/index.js~environment#bulkupdate",
    "class/src/Environment/index.js~Environment.html#instance-method-bulkUpdate",
    "src/Environment/index.js~Environment#bulkUpdate",
    "method"
  ],
  [
    "src/environment/index.js~environment#constructor",
    "class/src/Environment/index.js~Environment.html#instance-constructor-constructor",
    "src/Environment/index.js~Environment#constructor",
    "method"
  ],
  [
    "src/environment/index.js~environment#create",
    "class/src/Environment/index.js~Environment.html#instance-method-create",
    "src/Environment/index.js~Environment#create",
    "method"
  ],
  [
    "src/environment/index.js~environment#destroy",
    "class/src/Environment/index.js~Environment.html#instance-method-destroy",
    "src/Environment/index.js~Environment#destroy",
    "method"
  ],
  [
    "src/environment/index.js~environment#for",
    "class/src/Environment/index.js~Environment.html#instance-method-for",
    "src/Environment/index.js~Environment#for",
    "method"
  ],
  [
    "src/environment/index.js~environment#update",
    "class/src/Environment/index.js~Environment.html#instance-method-update",
    "src/Environment/index.js~Environment#update",
    "method"
  ],
  [
    "src/environment/index.js~variable",
    "typedef/index.html#static-typedef-Variable",
    "src/Environment/index.js~Variable",
    "typedef"
  ],
  [
    "src/environment/index.js~variableparams",
    "typedef/index.html#static-typedef-VariableParams",
    "src/Environment/index.js~VariableParams",
    "typedef"
  ],
  [
    "src/events/index.js",
    "file/src/Events/index.js.html",
    "src/Events/index.js",
    "file"
  ],
  [
    "src/events/index.js~appevents",
    "typedef/index.html#static-typedef-AppEvents",
    "src/Events/index.js~AppEvents",
    "typedef"
  ],
  [
    "src/events/index.js~event",
    "typedef/index.html#static-typedef-Event",
    "src/Events/index.js~Event",
    "typedef"
  ],
  [
    "src/events/index.js~eventcategory",
    "typedef/index.html#static-typedef-EventCategory",
    "src/Events/index.js~EventCategory",
    "typedef"
  ],
  [
    "src/events/index.js~eventtype",
    "typedef/index.html#static-typedef-EventType",
    "src/Events/index.js~EventType",
    "typedef"
  ],
  [
    "src/events/index.js~eventuser",
    "typedef/index.html#static-typedef-EventUser",
    "src/Events/index.js~EventUser",
    "typedef"
  ],
  [
    "src/events/index.js~events#constructor",
    "class/src/Events/index.js~Events.html#instance-constructor-constructor",
    "src/Events/index.js~Events#constructor",
    "method"
  ],
  [
    "src/events/index.js~events#for",
    "class/src/Events/index.js~Events.html#instance-method-for",
    "src/Events/index.js~Events#for",
    "method"
  ],
  [
    "src/events/index.js~events#listeventcategories",
    "class/src/Events/index.js~Events.html#instance-method-listEventCategories",
    "src/Events/index.js~Events#listEventCategories",
    "method"
  ],
  [
    "src/events/index.js~events#listeventtypes",
    "class/src/Events/index.js~Events.html#instance-method-listEventTypes",
    "src/Events/index.js~Events#listEventTypes",
    "method"
  ],
  [
    "src/events/index.js~eventspaginationopts",
    "typedef/index.html#static-typedef-EventsPaginationOpts",
    "src/Events/index.js~EventsPaginationOpts",
    "typedef"
  ],
  [
    "src/logs/index.js",
    "file/src/Logs/index.js.html",
    "src/Logs/index.js",
    "file"
  ],
  [
    "src/logs/index.js~applogsopts",
    "typedef/index.html#static-typedef-AppLogsOpts",
    "src/Logs/index.js~AppLogsOpts",
    "typedef"
  ],
  [
    "src/logs/index.js~archive",
    "typedef/index.html#static-typedef-Archive",
    "src/Logs/index.js~Archive",
    "typedef"
  ],
  [
    "src/logs/index.js~logs#archives",
    "class/src/Logs/index.js~Logs.html#instance-method-archives",
    "src/Logs/index.js~Logs#archives",
    "method"
  ],
  [
    "src/logs/index.js~logs#constructor",
    "class/src/Logs/index.js~Logs.html#instance-constructor-constructor",
    "src/Logs/index.js~Logs#constructor",
    "method"
  ],
  [
    "src/logs/index.js~logs#for",
    "class/src/Logs/index.js~Logs.html#instance-method-for",
    "src/Logs/index.js~Logs#for",
    "method"
  ],
  [
    "src/logs/index.js~logs#listenerfor",
    "class/src/Logs/index.js~Logs.html#instance-method-listenerFor",
    "src/Logs/index.js~Logs#listenerFor",
    "method"
  ],
  [
    "src/logs/listener.js",
    "file/src/Logs/listener.js.html",
    "src/Logs/listener.js",
    "file"
  ],
  [
    "src/logs/listener.js~logslistener#close",
    "class/src/Logs/listener.js~LogsListener.html#instance-method-close",
    "src/Logs/listener.js~LogsListener#close",
    "method"
  ],
  [
    "src/logs/listener.js~logslistener#constructor",
    "class/src/Logs/listener.js~LogsListener.html#instance-constructor-constructor",
    "src/Logs/listener.js~LogsListener#constructor",
    "method"
  ],
  [
    "src/logs/listener.js~logslistener#onlog",
    "class/src/Logs/listener.js~LogsListener.html#instance-method-onLog",
    "src/Logs/listener.js~LogsListener#onLog",
    "method"
  ],
  [
    "src/metrics/index.js",
    "file/src/Metrics/index.js.html",
    "src/Metrics/index.js",
    "file"
  ],
  [
    "src/metrics/index.js~metrictype",
    "typedef/index.html#static-typedef-MetricType",
    "src/Metrics/index.js~MetricType",
    "typedef"
  ],
  [
    "src/metrics/index.js~metrics#constructor",
    "class/src/Metrics/index.js~Metrics.html#instance-constructor-constructor",
    "src/Metrics/index.js~Metrics#constructor",
    "method"
  ],
  [
    "src/metrics/index.js~metrics#get",
    "class/src/Metrics/index.js~Metrics.html#instance-method-get",
    "src/Metrics/index.js~Metrics#get",
    "method"
  ],
  [
    "src/metrics/index.js~metrics#types",
    "class/src/Metrics/index.js~Metrics.html#instance-method-types",
    "src/Metrics/index.js~Metrics#types",
    "method"
  ],
  [
    "src/metrics/index.js~point",
    "typedef/index.html#static-typedef-Point",
    "src/Metrics/index.js~Point",
    "typedef"
  ],
  [
    "src/notificationplatforms/index.js",
    "file/src/NotificationPlatforms/index.js.html",
    "src/NotificationPlatforms/index.js",
    "file"
  ],
  [
    "src/notificationplatforms/index.js~notificationplatform",
    "typedef/index.html#static-typedef-NotificationPlatform",
    "src/NotificationPlatforms/index.js~NotificationPlatform",
    "typedef"
  ],
  [
    "src/notificationplatforms/index.js~notificationplatforms#constructor",
    "class/src/NotificationPlatforms/index.js~NotificationPlatforms.html#instance-constructor-constructor",
    "src/NotificationPlatforms/index.js~NotificationPlatforms#constructor",
    "method"
  ],
  [
    "src/notificationplatforms/index.js~notificationplatforms#list",
    "class/src/NotificationPlatforms/index.js~NotificationPlatforms.html#instance-method-list",
    "src/NotificationPlatforms/index.js~NotificationPlatforms#list",
    "method"
  ],
  [
    "src/notificationplatforms/list.js",
    "file/src/NotificationPlatforms/list.js.html",
    "src/NotificationPlatforms/list.js",
    "file"
  ],
  [
    "src/notifiers/index.js",
    "file/src/Notifiers/index.js.html",
    "src/Notifiers/index.js",
    "file"
  ],
  [
    "src/notifiers/index.js~notifier",
    "typedef/index.html#static-typedef-Notifier",
    "src/Notifiers/index.js~Notifier",
    "typedef"
  ],
  [
    "src/notifiers/index.js~notifiercreateparams",
    "typedef/index.html#static-typedef-NotifierCreateParams",
    "src/Notifiers/index.js~NotifierCreateParams",
    "typedef"
  ],
  [
    "src/notifiers/index.js~notifierupdateparams",
    "typedef/index.html#static-typedef-NotifierUpdateParams",
    "src/Notifiers/index.js~NotifierUpdateParams",
    "typedef"
  ],
  [
    "src/notifiers/index.js~notifiers#constructor",
    "class/src/Notifiers/index.js~Notifiers.html#instance-constructor-constructor",
    "src/Notifiers/index.js~Notifiers#constructor",
    "method"
  ],
  [
    "src/notifiers/index.js~notifiers#create",
    "class/src/Notifiers/index.js~Notifiers.html#instance-method-create",
    "src/Notifiers/index.js~Notifiers#create",
    "method"
  ],
  [
    "src/notifiers/index.js~notifiers#destroy",
    "class/src/Notifiers/index.js~Notifiers.html#instance-method-destroy",
    "src/Notifiers/index.js~Notifiers#destroy",
    "method"
  ],
  [
    "src/notifiers/index.js~notifiers#for",
    "class/src/Notifiers/index.js~Notifiers.html#instance-method-for",
    "src/Notifiers/index.js~Notifiers#for",
    "method"
  ],
  [
    "src/notifiers/index.js~notifiers#get",
    "class/src/Notifiers/index.js~Notifiers.html#instance-method-get",
    "src/Notifiers/index.js~Notifiers#get",
    "method"
  ],
  [
    "src/notifiers/index.js~notifiers#test",
    "class/src/Notifiers/index.js~Notifiers.html#instance-method-test",
    "src/Notifiers/index.js~Notifiers#test",
    "method"
  ],
  [
    "src/notifiers/index.js~notifiers#update",
    "class/src/Notifiers/index.js~Notifiers.html#instance-method-update",
    "src/Notifiers/index.js~Notifiers#update",
    "method"
  ],
  [
    "src/operations/index.js",
    "file/src/Operations/index.js.html",
    "src/Operations/index.js",
    "file"
  ],
  [
    "src/operations/index.js~operation",
    "typedef/index.html#static-typedef-Operation",
    "src/Operations/index.js~Operation",
    "typedef"
  ],
  [
    "src/operations/index.js~operations#constructor",
    "class/src/Operations/index.js~Operations.html#instance-constructor-constructor",
    "src/Operations/index.js~Operations#constructor",
    "method"
  ],
  [
    "src/operations/index.js~operations#operation",
    "class/src/Operations/index.js~Operations.html#instance-method-operation",
    "src/Operations/index.js~Operations#operation",
    "method"
  ],
  [
    "src/operations/utils.js",
    "file/src/Operations/utils.js.html",
    "src/Operations/utils.js",
    "file"
  ],
  [
    "src/operations/utils.js~operation#constructor",
    "class/src/Operations/utils.js~Operation.html#instance-constructor-constructor",
    "src/Operations/utils.js~Operation#constructor",
    "method"
  ],
  [
    "src/operations/utils.js~operation#created_at",
    "class/src/Operations/utils.js~Operation.html#instance-get-created_at",
    "src/Operations/utils.js~Operation#created_at",
    "member"
  ],
  [
    "src/operations/utils.js~operation#error",
    "class/src/Operations/utils.js~Operation.html#instance-get-error",
    "src/Operations/utils.js~Operation#error",
    "member"
  ],
  [
    "src/operations/utils.js~operation#finished_at",
    "class/src/Operations/utils.js~Operation.html#instance-get-finished_at",
    "src/Operations/utils.js~Operation#finished_at",
    "member"
  ],
  [
    "src/operations/utils.js~operation#id",
    "class/src/Operations/utils.js~Operation.html#instance-get-id",
    "src/Operations/utils.js~Operation#id",
    "member"
  ],
  [
    "src/operations/utils.js~operation#refresh",
    "class/src/Operations/utils.js~Operation.html#instance-method-refresh",
    "src/Operations/utils.js~Operation#refresh",
    "method"
  ],
  [
    "src/operations/utils.js~operation#setproperties",
    "class/src/Operations/utils.js~Operation.html#instance-method-setProperties",
    "src/Operations/utils.js~Operation#setProperties",
    "method"
  ],
  [
    "src/operations/utils.js~operation#status",
    "class/src/Operations/utils.js~Operation.html#instance-get-status",
    "src/Operations/utils.js~Operation#status",
    "member"
  ],
  [
    "src/operations/utils.js~operation#type",
    "class/src/Operations/utils.js~Operation.html#instance-get-type",
    "src/Operations/utils.js~Operation#type",
    "member"
  ],
  [
    "src/operations/utils.js~operation#wait",
    "class/src/Operations/utils.js~Operation.html#instance-method-wait",
    "src/Operations/utils.js~Operation#wait",
    "method"
  ],
  [
    "src/scmintegrations/index.js",
    "file/src/SCMIntegrations/index.js.html",
    "src/SCMIntegrations/index.js",
    "file"
  ],
  [
    "src/scmintegrations/index.js~key",
    "typedef/index.html#static-typedef-Key",
    "src/SCMIntegrations/index.js~Key",
    "typedef"
  ],
  [
    "src/scmintegrations/index.js~organization",
    "typedef/index.html#static-typedef-Organization",
    "src/SCMIntegrations/index.js~Organization",
    "typedef"
  ],
  [
    "src/scmintegrations/index.js~pullrequest",
    "typedef/index.html#static-typedef-PullRequest",
    "src/SCMIntegrations/index.js~PullRequest",
    "typedef"
  ],
  [
    "src/scmintegrations/index.js~repository",
    "typedef/index.html#static-typedef-Repository",
    "src/SCMIntegrations/index.js~Repository",
    "typedef"
  ],
  [
    "src/scmintegrations/index.js~scmintegration",
    "typedef/index.html#static-typedef-SCMIntegration",
    "src/SCMIntegrations/index.js~SCMIntegration",
    "typedef"
  ],
  [
    "src/scmintegrations/index.js~scmintegrationcreateopts",
    "typedef/index.html#static-typedef-SCMIntegrationCreateOpts",
    "src/SCMIntegrations/index.js~SCMIntegrationCreateOpts",
    "typedef"
  ],
  [
    "src/scmintegrations/index.js~scmintegrations#all",
    "class/src/SCMIntegrations/index.js~SCMIntegrations.html#instance-method-all",
    "src/SCMIntegrations/index.js~SCMIntegrations#all",
    "method"
  ],
  [
    "src/scmintegrations/index.js~scmintegrations#constructor",
    "class/src/SCMIntegrations/index.js~SCMIntegrations.html#instance-constructor-constructor",
    "src/SCMIntegrations/index.js~SCMIntegrations#constructor",
    "method"
  ],
  [
    "src/scmintegrations/index.js~scmintegrations#create",
    "class/src/SCMIntegrations/index.js~SCMIntegrations.html#instance-method-create",
    "src/SCMIntegrations/index.js~SCMIntegrations#create",
    "method"
  ],
  [
    "src/scmintegrations/index.js~scmintegrations#destroy",
    "class/src/SCMIntegrations/index.js~SCMIntegrations.html#instance-method-destroy",
    "src/SCMIntegrations/index.js~SCMIntegrations#destroy",
    "method"
  ],
  [
    "src/scmintegrations/index.js~scmintegrations#find",
    "class/src/SCMIntegrations/index.js~SCMIntegrations.html#instance-method-find",
    "src/SCMIntegrations/index.js~SCMIntegrations#find",
    "method"
  ],
  [
    "src/scmintegrations/index.js~scmintegrations#importsshkeys",
    "class/src/SCMIntegrations/index.js~SCMIntegrations.html#instance-method-importSSHKeys",
    "src/SCMIntegrations/index.js~SCMIntegrations#importSSHKeys",
    "method"
  ],
  [
    "src/scmintegrations/index.js~scmintegrations#organizations",
    "class/src/SCMIntegrations/index.js~SCMIntegrations.html#instance-method-organizations",
    "src/SCMIntegrations/index.js~SCMIntegrations#organizations",
    "method"
  ],
  [
    "src/scmintegrations/index.js~scmintegrations#searchpullrequests",
    "class/src/SCMIntegrations/index.js~SCMIntegrations.html#instance-method-searchPullRequests",
    "src/SCMIntegrations/index.js~SCMIntegrations#searchPullRequests",
    "method"
  ],
  [
    "src/scmintegrations/index.js~scmintegrations#searchrepositories",
    "class/src/SCMIntegrations/index.js~SCMIntegrations.html#instance-method-searchRepositories",
    "src/SCMIntegrations/index.js~SCMIntegrations#searchRepositories",
    "method"
  ],
  [
    "src/scmintegrations/index.js~scmtype",
    "typedef/index.html#static-typedef-SCMType",
    "src/SCMIntegrations/index.js~SCMType",
    "typedef"
  ],
  [
    "src/scmrepolinks/index.js",
    "file/src/SCMRepoLinks/index.js.html",
    "src/SCMRepoLinks/index.js",
    "file"
  ],
  [
    "src/scmrepolinks/index.js~branch",
    "typedef/index.html#static-typedef-Branch",
    "src/SCMRepoLinks/index.js~Branch",
    "typedef"
  ],
  [
    "src/scmrepolinks/index.js~pullrequest",
    "typedef/index.html#static-typedef-PullRequest",
    "src/SCMRepoLinks/index.js~PullRequest",
    "typedef"
  ],
  [
    "src/scmrepolinks/index.js~scmrepolink",
    "typedef/index.html#static-typedef-SCMRepoLink",
    "src/SCMRepoLinks/index.js~SCMRepoLink",
    "typedef"
  ],
  [
    "src/scmrepolinks/index.js~scmrepolinkcreateopts",
    "typedef/index.html#static-typedef-SCMRepoLinkCreateOpts",
    "src/SCMRepoLinks/index.js~SCMRepoLinkCreateOpts",
    "typedef"
  ],
  [
    "src/scmrepolinks/index.js~scmrepolinkupdateopts",
    "typedef/index.html#static-typedef-SCMRepoLinkUpdateOpts",
    "src/SCMRepoLinks/index.js~SCMRepoLinkUpdateOpts",
    "typedef"
  ],
  [
    "src/scmrepolinks/index.js~scmrepolinks#branches",
    "class/src/SCMRepoLinks/index.js~SCMRepoLinks.html#instance-method-branches",
    "src/SCMRepoLinks/index.js~SCMRepoLinks#branches",
    "method"
  ],
  [
    "src/scmrepolinks/index.js~scmrepolinks#constructor",
    "class/src/SCMRepoLinks/index.js~SCMRepoLinks.html#instance-constructor-constructor",
    "src/SCMRepoLinks/index.js~SCMRepoLinks#constructor",
    "method"
  ],
  [
    "src/scmrepolinks/index.js~scmrepolinks#create",
    "class/src/SCMRepoLinks/index.js~SCMRepoLinks.html#instance-method-create",
    "src/SCMRepoLinks/index.js~SCMRepoLinks#create",
    "method"
  ],
  [
    "src/scmrepolinks/index.js~scmrepolinks#destroy",
    "class/src/SCMRepoLinks/index.js~SCMRepoLinks.html#instance-method-destroy",
    "src/SCMRepoLinks/index.js~SCMRepoLinks#destroy",
    "method"
  ],
  [
    "src/scmrepolinks/index.js~scmrepolinks#find",
    "class/src/SCMRepoLinks/index.js~SCMRepoLinks.html#instance-method-find",
    "src/SCMRepoLinks/index.js~SCMRepoLinks#find",
    "method"
  ],
  [
    "src/scmrepolinks/index.js~scmrepolinks#manualdeploy",
    "class/src/SCMRepoLinks/index.js~SCMRepoLinks.html#instance-method-manualDeploy",
    "src/SCMRepoLinks/index.js~SCMRepoLinks#manualDeploy",
    "method"
  ],
  [
    "src/scmrepolinks/index.js~scmrepolinks#manualreviewapp",
    "class/src/SCMRepoLinks/index.js~SCMRepoLinks.html#instance-method-manualReviewApp",
    "src/SCMRepoLinks/index.js~SCMRepoLinks#manualReviewApp",
    "method"
  ],
  [
    "src/scmrepolinks/index.js~scmrepolinks#pulls",
    "class/src/SCMRepoLinks/index.js~SCMRepoLinks.html#instance-method-pulls",
    "src/SCMRepoLinks/index.js~SCMRepoLinks#pulls",
    "method"
  ],
  [
    "src/scmrepolinks/index.js~scmrepolinks#update",
    "class/src/SCMRepoLinks/index.js~SCMRepoLinks.html#instance-method-update",
    "src/SCMRepoLinks/index.js~SCMRepoLinks#update",
    "method"
  ],
  [
    "src/tokens/index.js",
    "file/src/Tokens/index.js.html",
    "src/Tokens/index.js",
    "file"
  ],
  [
    "src/tokens/index.js~token",
    "typedef/index.html#static-typedef-Token",
    "src/Tokens/index.js~Token",
    "typedef"
  ],
  [
    "src/tokens/index.js~tokens#constructor",
    "class/src/Tokens/index.js~Tokens.html#instance-constructor-constructor",
    "src/Tokens/index.js~Tokens#constructor",
    "method"
  ],
  [
    "src/tokens/index.js~tokens#exchange",
    "class/src/Tokens/index.js~Tokens.html#instance-method-exchange",
    "src/Tokens/index.js~Tokens#exchange",
    "method"
  ],
  [
    "src/users/index.js",
    "file/src/Users/index.js.html",
    "src/Users/index.js",
    "file"
  ],
  [
    "src/users/index.js~accountupdateparams",
    "typedef/index.html#static-typedef-AccountUpdateParams",
    "src/Users/index.js~AccountUpdateParams",
    "typedef"
  ],
  [
    "src/users/index.js~githubprofile",
    "typedef/index.html#static-typedef-GithubProfile",
    "src/Users/index.js~GithubProfile",
    "typedef"
  ],
  [
    "src/users/index.js~user",
    "typedef/index.html#static-typedef-User",
    "src/Users/index.js~User",
    "typedef"
  ],
  [
    "src/users/index.js~users#constructor",
    "class/src/Users/index.js~Users.html#instance-constructor-constructor",
    "src/Users/index.js~Users#constructor",
    "method"
  ],
  [
    "src/users/index.js~users#self",
    "class/src/Users/index.js~Users.html#instance-method-self",
    "src/Users/index.js~Users#self",
    "method"
  ],
  [
    "src/users/index.js~users#updateaccount",
    "class/src/Users/index.js~Users.html#instance-method-updateAccount",
    "src/Users/index.js~Users#updateAccount",
    "method"
  ],
  [
    "src/errors.js",
    "file/src/errors.js.html",
    "src/errors.js",
    "file"
  ],
  [
    "src/errors.js~apierror#constructor",
    "class/src/errors.js~APIError.html#instance-constructor-constructor",
    "src/errors.js~APIError#constructor",
    "method"
  ],
  [
    "src/errors.js~apierror#data",
    "class/src/errors.js~APIError.html#instance-get-data",
    "src/errors.js~APIError#data",
    "member"
  ],
  [
    "src/errors.js~apierror#stack",
    "class/src/errors.js~APIError.html#instance-member-stack",
    "src/errors.js~APIError#stack",
    "member"
  ],
  [
    "src/errors.js~apierror#status",
    "class/src/errors.js~APIError.html#instance-get-status",
    "src/errors.js~APIError#status",
    "member"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index.js~client#addons",
    "class/src/index.js~Client.html#instance-member-Addons",
    "src/index.js~Client#Addons",
    "member"
  ],
  [
    "src/index.js~client#apps",
    "class/src/index.js~Client.html#instance-member-Apps",
    "src/index.js~Client#Apps",
    "member"
  ],
  [
    "src/index.js~client#collaborators",
    "class/src/index.js~Client.html#instance-member-Collaborators",
    "src/index.js~Client#Collaborators",
    "member"
  ],
  [
    "src/index.js~client#containers",
    "class/src/index.js~Client.html#instance-member-Containers",
    "src/index.js~Client#Containers",
    "member"
  ],
  [
    "src/index.js~client#deployments",
    "class/src/index.js~Client.html#instance-member-Deployments",
    "src/index.js~Client#Deployments",
    "member"
  ],
  [
    "src/index.js~client#domains",
    "class/src/index.js~Client.html#instance-member-Domains",
    "src/index.js~Client#Domains",
    "member"
  ],
  [
    "src/index.js~client#environment",
    "class/src/index.js~Client.html#instance-member-Environment",
    "src/index.js~Client#Environment",
    "member"
  ],
  [
    "src/index.js~client#events",
    "class/src/index.js~Client.html#instance-member-Events",
    "src/index.js~Client#Events",
    "member"
  ],
  [
    "src/index.js~client#logs",
    "class/src/index.js~Client.html#instance-member-Logs",
    "src/index.js~Client#Logs",
    "member"
  ],
  [
    "src/index.js~client#metrics",
    "class/src/index.js~Client.html#instance-member-Metrics",
    "src/index.js~Client#Metrics",
    "member"
  ],
  [
    "src/index.js~client#notificationplatforms",
    "class/src/index.js~Client.html#instance-member-NotificationPlatforms",
    "src/index.js~Client#NotificationPlatforms",
    "member"
  ],
  [
    "src/index.js~client#notifiers",
    "class/src/index.js~Client.html#instance-member-Notifiers",
    "src/index.js~Client#Notifiers",
    "member"
  ],
  [
    "src/index.js~client#operations",
    "class/src/index.js~Client.html#instance-member-Operations",
    "src/index.js~Client#Operations",
    "member"
  ],
  [
    "src/index.js~client#scmintegrations",
    "class/src/index.js~Client.html#instance-member-SCMIntegrations",
    "src/index.js~Client#SCMIntegrations",
    "member"
  ],
  [
    "src/index.js~client#scmrepolinks",
    "class/src/index.js~Client.html#instance-member-SCMRepoLinks",
    "src/index.js~Client#SCMRepoLinks",
    "member"
  ],
  [
    "src/index.js~client#tokens",
    "class/src/index.js~Client.html#instance-member-Tokens",
    "src/index.js~Client#Tokens",
    "member"
  ],
  [
    "src/index.js~client#users",
    "class/src/index.js~Client.html#instance-member-Users",
    "src/index.js~Client#Users",
    "member"
  ],
  [
    "src/index.js~client#apiclient",
    "class/src/index.js~Client.html#instance-method-apiClient",
    "src/index.js~Client#apiClient",
    "method"
  ],
  [
    "src/index.js~client#authapiclient",
    "class/src/index.js~Client.html#instance-method-authApiClient",
    "src/index.js~Client#authApiClient",
    "method"
  ],
  [
    "src/index.js~client#constructor",
    "class/src/index.js~Client.html#instance-constructor-constructor",
    "src/index.js~Client#constructor",
    "method"
  ],
  [
    "src/index.js~client#unauthenticatedclient",
    "class/src/index.js~Client.html#instance-method-unauthenticatedClient",
    "src/index.js~Client#unauthenticatedClient",
    "method"
  ],
  [
    "src/meta.js",
    "file/src/meta.js.html",
    "src/meta.js",
    "file"
  ],
  [
    "src/meta.js~paginationmeta",
    "typedef/index.html#static-typedef-PaginationMeta",
    "src/meta.js~PaginationMeta",
    "typedef"
  ],
  [
    "src/meta.js~paginationopts",
    "typedef/index.html#static-typedef-PaginationOpts",
    "src/meta.js~PaginationOpts",
    "typedef"
  ],
  [
    "src/utils.js",
    "file/src/utils.js.html",
    "src/utils.js",
    "file"
  ]
]